#!/usr/bin/env bash

set -euo pipefail

program="fcb-exec"

function lint() {
  check_extern_commands "cargo"
  cargo clippy --no-deps
}

function test() {
  check_extern_commands "cargo"
  cargo test 
}

function check_extern_commands() {
    for cmd in "${@}"; do
    if ! which "$cmd" > /dev/null 2>&1; then 
      echo "${program}: please install $cmd to proceed." >&2
      exit 1
    fi
    done
}

"$@"


