#!/usr/bin/env bash

set -euo pipefail

program="fcb-exec"

function create_archive() {
  check_extern_commands "cargo" "tar"

  rust_target="$1"
  archive_path="$2"

  if [ -d "./target/$rust_target" ]; then
    rm -rf "./target/$rust_target"
  fi

  cargo build --release --locked --target "$rust_target"
  tar -C "./target/$rust_target/release" -czvf "$archive_path" "fcb"
}

function create_checksum_darwin() {
  check_extern_commands "sha256sum"
  sha256sum "./target/$1/release/fcb"
}

function create_checksum_linux() {
  check_extern_commands "shasum"
  shasum -a 256 "./target/$1/release/fcb"
}

function create_checksum() {
  check_extern_commands "cargo"

  rust_target="$1"

  if ! [ -d "./target/$rust_target" ]; then
    cargo build --release --locked --target "$rust_target"
  fi

  if [ "$(uname -s)" == "Darwin" ]; then
    create_checksum_darwin "$rust_target"
  else
    create_checksum_linux "$rust_target"
  fi
}

function lint() {
  check_extern_commands "cargo"
  cargo clippy --no-deps
}

function test() {
  check_extern_commands "cargo"
  cargo test
}

function check_extern_commands() {
  for cmd in "${@}"; do
    if ! which "$cmd" >/dev/null 2>&1; then
      echo "${program}: please install $cmd to proceed." >&2
      exit 1
    fi
  done
}

"$@"
