#!/usr/bin/env bash

set -euo pipefail

program="fcb-exec"

function create_archive() {
  check_extern_commands "cargo" "tar"

  rust_target="$1"
  archive_path="$2"

  if [ -d "./target/$rust_target" ]; then
      rm -rf "./target/$rust_target"
  fi

  cargo build --release --locked --target "$rust_target"
  tar czvf "$archive_path" "./target/$rust_target/release/fcb"
}

function create_checksum() {
  sha_cmd=""
  sha_opts=()

  if [ "$(uname -s)" == "Darwin" ]; then
    sha_cmd="sha256sum"
  else
    sha_cmd="shasum"
    sha_opts+=("-a" "256")
  fi

  check_extern_commands "cargo" "$sha_cmd"

  rust_target="$1"

  if ! [ -d "./target/$rust_target" ]; then
    cargo build --release --locked --target "$rust_target"
  fi 

  "$sha_cmd" "${sha_opts[@]}" "./target/$rust_target/release/fcb"
}

function lint() {
  check_extern_commands "cargo"
  cargo clippy --no-deps
}

function test() {
  check_extern_commands "cargo"
  cargo test 
}

function check_extern_commands() {
    for cmd in "${@}"; do
    if ! which "$cmd" > /dev/null 2>&1; then 
      echo "${program}: please install $cmd to proceed." >&2
      exit 1
    fi
    done
}

"$@"


